
export const productConstants = {
    GET_ALL_PRODUCT_REQUEST:'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_SUCCESS:'GET_ALL_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_FAILURE:'GET_ALL_PRODUCT_FAILURE',

    

}
export const cartConstants = {
    ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
    

    GET_CART_ITEM_REQUEST: "GET_CART_ITEM_REQUEST",
    GET_CART_ITEM_SUCCESS:"GET_CART_ITEM_SUCCESS",
  
    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
    RESET_CART: "RESET_CART",
  };
  